# Add projects here in the following format:

# <projectname>:
#	Type: <projectType>
#	Exclude: <tasks to exclude when running the standard process
#	Config: 
#		<optional condiguration>

# Valid project types and their process:
#	App => Any Windows, Web or Console app | Process: Clean, Compile, Pack, Push, Release, Deploy
#	Package => NuGet package | Process: Clean, Compile, Pack, Push
#	VsTest => Project with Ms Tests | Process: Clean, Compile, Test
#	Xunit => Project with Xunit Tests | Process: Clean, Compile, Test
#   StandaloneWebJob => Project with an Azure Webjob that is deployed independently | Process: Clean, Compile, Pack, Push, Release, Deploy
#		configuration sample:
#			<projectName>:
#				Type: StandaloneWebJob
#				Config: 
#					RunMode: <continuous | triggered>
#   Embedded => Project with an Azure Webjob that is deployed in another project in the solution | Process: Clean, Compile
#		Configuration sample:
#			<projectName>:
#				Type: EmbeddedWebJob
#				Config: 
#					Target: <project name to embed into>
#					RunMode: <continuous | triggered>

#Appy.GitDb.Benchmark:
#	Type: App
#	Exclude: "pack, push, release, deploy"
Appy.GitDb.Local:
	Type: Package
Appy.GitDb.Remote:
	Type: Package
Appy.GitDb.Server:
	Type: App
Appy.GitDb.Tests:
	Type: Xunit
Appy.GitDb.Watcher:
	Type: Package
