# Add projects here in the following format:

# <projectname>:
#	Type: <projectType>
#	Exclude: <tasks to exclude when running the standard process
#	Config: 
#		<optional condiguration>

# Valid project types and their process:
#	App => Any Windows, Web or Console app | Process: Clean, Compile, Pack, Push, Release, Deploy
#	Package => NuGet package | Process: Clean, Compile, Pack, Push
#	Xunit => Project with Xunit Tests | Process: Clean, Compile, Test
Appy.GitDb.Benchmark:
	Type: App
	Exclude: "pack, push, release, deploy"
Appy.GitDb.Local:
	Type: Package
Appy.GitDb.Remote:
	Type: Package
Appy.GitDb.Server:
	Type: App
Appy.GitDb.Tests:
	Type: Xunit
Appy.GitDb.Watcher:
	Type: Package
Appy.GitDb.NetCore.Server:
	Type: App, AppPackage
